### ISSUE TITLE
Missing testcase name breaks forwarding

### ISSUE THREAD

**Issue by s1hofmann** [sakuli/sakuli-enterprise-forwarder#47]
Testcase instances which lack a name, but provide warning and ciritical times break result forwarding.
In this case (tested with Icings setup), only a testsuite result is forwarded, no results for testcases and -steps.

Broken sample:

```js
(async () => {
    const testCase = new TestCase(45, 60);
    try {
        await _navigateTo("https://sakuli.io");                  // 1
        testCase.endOfStep("Open Landing Page",100, 150);                      // 2
        await _highlight(_link("TAKE ME TO THE DOCS AND GET STARTED"))
        await _click(_link("TAKE ME TO THE DOCS AND GET STARTED"));                         // 3
        let handlers = await driver.getAllWindowHandles();
        //Logger.logInfo(`HANDLERS: ${handlers}`)
        await driver.switchTo().window(handlers[1]);
        testCase.endOfStep("Navigate to Getting Started",30,100);            // 4
        await _highlight(_code("npm init"));                            // 5
        testCase.endOfStep("Find npm init code sample");
    } catch (e) {
        await testCase.handleException(e);
    } finally {
        await testCase.saveResult();
    }
})();
```

When either skipping both testcase name and warning / critical thresholds, forwardings works fine again.

Acc. Crit.:

- [ ] Root cause analysed

**Comment by svettwer** [comment]
The root cause is located in `test-case.class.ts`
```typescript
constructor(
      readonly caseId: string = "Testcase",
      readonly warningTime: number = 0,
      readonly criticalTime: number = 0,
      public _imagePaths: string[] = []
    ) {
     ...
   }
```

With this constructor, `new TestCase(42, 84)` showing the following output.
```
sakulie2e_prometheus       | Writing logs to: legacy-suite/_logs/sakuli.log
sakulie2e_prometheus       | Started execution
sakulie2e_prometheus       | → Started Testsuite integrationtest
sakulie2e_prometheus       |   → Started Testcase 42
```

Instead of interpreting the numbers as `warningTime` and `criticalTime` they are mapped by their position as `caseId` and `warningTime`. Because constructor overloading is not possible in JS, this is an illegal call anyways. As the types mismatch during runtime, this might cause some errors which are not forwarded to the user as escalated error in the forwarders are logged to debug level instead of error.

`connect-forwarder-to-test-execution-context.function.ts`
```typescript
for (const forwarding of forwardings) {
      try {
        await forwarding;
      } catch (e) {
        ctx.logger.debug(`There were errors during forwarding`);
      }
    }
```
Anyways, even when I set the level to debug, nothing is logged. So the journey has not ended yet.

*to be continued*

**Comment by svettwer** [comment]
The root cause is definitely the invalid constructor usage.
If one would manually remap or just convert the number into string, `""+id`, everything works as expected. On the other hand, I have no clue why and how such a behavior is possible at all.

```typescript
 return class SakuliTestCase implements TestCase {
    constructor(
      readonly caseId: string = "Testcase",
      readonly warningTime: number = 0,
      readonly criticalTime: number = 0,
      public _imagePaths: string[] = []
    ) {
      ctx.startTestCase({ id: ""+caseId, warningTime, criticalTime });
      ctx.startTestStep({});
      nutConfig.imagePaths = [cwd()];
      const testFolder = throwIfAbsent(
        currentTestFolder,
        new Error("No testcase folder provided")
      );
      nutConfig.addImagePath(testFolder);
      this.addImagePaths(..._imagePaths);
    }
```

My attempt would be to check the parameters of the `SakuliTestCase` constructor and: 
1. try to correct the mapping to something useful
2. Throw an exception in case the parameters are invalid or not matching the given types. 

I'd prefer the second attempt. The first attempt comes with a lot of crystal ball reading which might end up in a very complex *"what if some one puts in parameters like that"* logic.
Therefore I'd throw, let Sakuli die, tell the user that he should use the constructor as it is intended and that's it. I think this is not a breaking change in general. We just fix a bug that is already there, bending the Sakuli 1 legacy compatibility a little bit.
